### ISSUE TITLE
cannot build on step 1.2 / 无法在步骤 1.2 上进行构建

### ISSUE THREAD

**Issue by fdemolde** [dolphindb/api-rust#2]
Hi, I am trying to use cargo build on the step 1.2 of the README  but it cannot compile due to this error:
/usr/bin/ld: cannot find -lwrapper: No such file or directory
          collect2: error: ld returned 1 exit status
Could you help me please?

你好，我正在尝试使用 README 第 1.2 步的货物编译功能，但由于这个错误而无法编译：
/usr/bin/ld: cannot find -lwrapper: No such file or directory
          collect2: error: ld returned 1 exit status
您能帮帮我吗？

**Comment by sunhuiquan** [comment]
I guess it's because you placed the entire 'api-rust' folder into your project, rather than the 'api' folder within 'api-rust'. I was able to reproduce the same error in this way. 

![image](https://github.com/dolphindb/api-rust/assets/73767064/05e3606a-865f-4d15-93b2-819d857cd20b)

![image](https://github.com/dolphindb/api-rust/assets/73767064/a2580244-9c55-49fc-9c34-5d7c15f564b6)

If this is the cause of the problem, you should only place the 'api' folder from 'api-rust' into your project, and change the dependency to ddb = {path = "./api"}.

If the issue is not caused by the reason mentioned earlier, please provide the following information for further analysis:

1. The contents of the cargo.toml file in your project.
2. The Rust version information output by the rustup show command.
3. The library path information output by the echo $LD_LIBRARY_PATH command.

**Comment by fdemolde** [comment]
Good evening and thank you for your help.
Only the api folder was in the project folder.
Here are the info requested :

1: ![image](https://github.com/dolphindb/api-rust/assets/44402144/b30dbb70-a875-42fb-81bc-8f714dcb3fbe)

2: Default host: x86_64-unknown-linux-gnu
rustup home:  /home/floriandemolder/.rustup

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.75.0 (82e1608df 2023-12-21)

3: /home/username/Documents/RUST/SLINT+dolphinDB/dbtest/api/src/apic

**Comment by sunhuiquan** [comment]
Thank you for providing the details.
Please execute 'find /somewhere/dbtest -name libwrapper.a' to provide the path of the library file, and also provide the error output information from 'cargo build'.

**Comment by fdemolde** [comment]
Good evening,
Find command: /home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/api/src/apic/libwrapper.a
Cargo build output:

    Compiling ddb v0.1.0 (/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/api)
   Compiling dbtest v0.1.0 (/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest)
warning: unused imports: `c_char`, `c_double`, `c_float`, `c_int`, `c_longlong`, `c_short`, `c_void`
 --> src/main.rs:3:12
  |
3 | use libc::{c_void,c_int,c_char,c_short,c_longlong,c_float,c_double};
  |            ^^^^^^ ^^^^^ ^^^^^^ ^^^^^^^ ^^^^^^^^^^ ^^^^^^^ ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::ffi::CString`
 --> src/main.rs:4:5
  |
4 | use std::ffi::CString;
  |     ^^^^^^^^^^^^^^^^^

warning: unused import: `std::ffi::CStr`
 --> src/main.rs:5:5
  |
5 | use std::ffi::CStr;
  |     ^^^^^^^^^^^^^^

warning: unused import: `std::str`
 --> src/main.rs:6:5
  |
6 | use std::str;
  |     ^^^^^^^^

warning: unused import: `crate::ddb::Defobj`
 --> src/main.rs:7:5
  |
7 | use crate::ddb::Defobj;
  |     ^^^^^^^^^^^^^^^^^^

error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/somewhere/.cargo/bin:/home/somewhere/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcQ2DoLy/symbols.o" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps/dbtest-e1c7af7b7adb358d.1h5pp9utsnqxqzc2.rcgu.o" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps/dbtest-e1c7af7b7adb358d.2vv4yc9hnr82jdq2.rcgu.o" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps/dbtest-e1c7af7b7adb358d.3ywc229vpwglw3nl.rcgu.o" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps/dbtest-e1c7af7b7adb358d.4xdb0oiapplye238.rcgu.o" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps/dbtest-e1c7af7b7adb358d.nwc0q47u9l7pbi9.rcgu.o" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps/dbtest-e1c7af7b7adb358d.41q202qmulsjskcr.rcgu.o" "-Wl,--as-needed" "-L" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps" "-L" ".api/src/apic/" "-L" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps/libddb-e1741b0658506d43.rlib" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps/liblibc-a9fa19dd18f65bfc.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-90f6ddbf82de36ec.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-480c41e9d4e1f677.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-db744c0ca03eed1d.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-8ba652dc7d4b285a.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-d5f4520a9ebc0d58.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-4ad84de58f0cb463.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-0d10aae2e0f38735.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-0c17cff739e6745b.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-b29e17139dde1aa8.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-1f975299829cc7bd.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-86bae3bc3079f89b.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-321b82c30dffdf5f.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-3dd8a6810a0bdfef.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-eb39a61c0c879984.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-aa769569f91c3548.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-510a192a50a983ed.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-0577018320f99037.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-193cf992125ccd4c.rlib" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-8e138eaf26ebb4a8.rlib" "-Wl,-Bdynamic" "-lwrapper" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/somewhere/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/target/debug/deps/dbtest-e1c7af7b7adb358d" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lwrapper: No such file or directory
          collect2: error: ld returned 1 exit status
          

warning: `dbtest` (bin "dbtest") generated 5 warnings
error: could not compile `dbtest` (bin "dbtest") due to previous error; 5 warnings emitted


Best regards

**Comment by sunhuiquan** [comment]
![image](https://github.com/dolphindb/api-rust/assets/73767064/893226b2-c88f-45f6-b105-58d29d4d5f28)
Good evening.
The path used for '-L' '.api/src/apic/' in this picture appears to be incorrect, as there is no '.api' directory. 
Please try running 'export LD_LIBRARY_PATH=/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/api/src/apic' and then attempt again.


By the way, this library has not been maintained for a long time, and it is expected that a rewritten version will be released in May this year. The new version will no longer call the DolphinDB C++ API, but will be implemented purely using Rust. You can use the new version later.

**Comment by fdemolde** [comment]
Good evening,  
the new attempt failed but no problem, I can wait the new version.
Thank you for your help and the info.
Best regards.

**Comment by ShiLu1211** [comment]
> ![image](https://private-user-images.githubusercontent.com/73767064/324144151-893226b2-c88f-45f6-b105-58d29d4d5f28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjc1NzMsIm5iZiI6MTcyMjMyNzI3MywicGF0aCI6Ii83Mzc2NzA2NC8zMjQxNDQxNTEtODkzMjI2YjItYzg4Zi00NWY2LWIxMDUtNThkMjlkNGQ1ZjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA4MTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYzdmNzI4ZDc0NTQzZjkwNmJkNDE0ZjVlOGVjYzMxNGQ1MzY2YTkwZTkwOGM0N2ViNDhmZTc5MjBkNjU2NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UnCnSu1orJLhVvlgtXapxyDnPk9JhNM189CE_9M1MaA) Good evening. The path used for '-L' '.api/src/apic/' in this picture appears to be incorrect, as there is no '.api' directory. Please try running 'export LD_LIBRARY_PATH=/home/somewhere/Documents/RUST/SLINT+dolphinDB/dbtest/api/src/apic' and then attempt again.
> 
> By the way, this library has not been maintained for a long time, and it is expected that a rewritten version will be released in May this year. The new version will no longer call the DolphinDB C++ API, but will be implemented purely using Rust. You can use the new version later.

Looking forward to the rust version.
